# Use uma imagem base oficial do Python
FROM python:3.11-slim

# Diretório de trabalho
WORKDIR /app

# Copiar os arquivos necessários para o contêiner
COPY requirements.txt requirements.txt
COPY app.py app.py

# Instalar dependências
RUN pip install --no-cache-dir -r requirements.txt

# Expor a porta 5000 para o Flask
EXPOSE 5000

# Comando para rodar a aplicação
CMD ["python", "app.py"]
