# name: Deploy to ECS

# on:
#   push:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v2
    
#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: us-east-1

#     - name: Deploy to ECS
#       run: |
#         aws deploy create-deployment \
#           --application-name ecs-demo-app \
#           --deployment-group-name ecs-deployment-group \
#           --revision '{
#             "revisionType": "AppSpecContent",
#             "appSpecContent": {
#               "content": "{
#                 \"version\": 0.0,
#                 \"Resources\": [{
#                   \"TargetService\": {
#                     \"Type\": \"AWS::ECS::Service\",
#                     \"Properties\": {
#                       \"TaskDefinition\": \"arn:aws:ecs:us-east-1:YOUR_ACCOUNT_ID:task-definition/demo-teste\",
#                       \"LoadBalancerInfo\": {
#                         \"ContainerName\": \"app\",
#                         \"ContainerPort\": 5000
#                       },
#                       \"PlatformVersion\": \"LATEST\",
#                       \"NetworkConfiguration\": {
#                         \"AwsvpcConfiguration\": {
#                           \"Subnets\": [\"YOUR_SUBNET_ID\"],
#                           \"SecurityGroups\": [\"YOUR_SECURITY_GROUP_ID\"],
#                           \"AssignPublicIp\": \"ENABLED\"
#                         }
#                       }
#                     }
#                   }
#                 }]
#               }"
#             }
#           }'