name: "DEV DEPLOY"

on:
  push:
    branches:
      - dev 

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::058264525554:role/github-actions-OpsXandao-pipeline"
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "alexandre-us-east-1-tarraform-lock"
      aws-lock-dynamodb-table: "alexandre-us-east-1-terraform-lock"