name: "DEV DEPLOY"

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::058264525554:role/github-actions-OpsXandao-pipeline
          aws-region: us-east-1

      - name: Create AppSpec file
        run: |
          cat > appspec.json << 'EOF'
          {
            "version": 0.0,
            "Resources": [{
              "TargetService": {
                "Type": "AWS::ECS::Service",
                "Properties": {
                  "TaskDefinition": "demo-teste",
                  "LoadBalancerInfo": {
                    "ContainerName": "app",
                    "ContainerPort": 5000
                  }
                }
              }
            }]
          }
          EOF

      - name: Deploy to ECS
        run: |
          aws deploy create-deployment \
            --application-name ecs-demo-app \
            --deployment-group-name ecs-deployment-group \
            --revision "{\"revisionType\": \"AppSpecContent\", \"appSpecContent\": {\"content\": $(cat appspec.json | jq -c tostring)}}"