name: "DEV DEPLOY"

on:
  push:
    branches:
      - dev 

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      aws-assume-role-arn: "arn:aws:iam::058264525554:role/github-actions-OpsXandao-pipeline"
      # aws-region: "us-east-1"