name: "DEV DEPLOY"

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  APP_NAME: ecs-demo-app
  DEPLOYMENT_GROUP: ecs-deployment-group
  CONTAINER_IMAGE: 03021914/blue-green:v2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::058264525554:role/github-actions-OpsXandao-pipeline
          aws-region: us-east-1

      - name: Deploy to ECS
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.APP_NAME }} \
            --deployment-group-name ${{ env.DEPLOYMENT_GROUP }} \
            --revision '{
              "revisionType": "AppSpecContent",
              "appSpecContent": {
                "content": "{
                  \"version\": 0.0,
                  \"Resources\": [{
                    \"TargetService\": {
                      \"Type\": \"AWS::ECS::Service\",
                      \"Properties\": {
                        \"TaskDefinition\": \"demo-teste\",
                        \"LoadBalancerInfo\": {
                          \"ContainerName\": \"app\",
                          \"ContainerPort\": 5000
                        }
                      }
                    }
                  }]
                }"
              }
            }'