name: "Terraform Workflow"

on:
  workflow_call:
    inputs:
      aws-assume-role-arn:
        type: string
        required: true
      aws-region:
        type: string
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Access another repository
        env:
          PAT: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git clone https://OpsXandao:${PAT}@github.com/OpsXandao/modules-terraform.git

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-assume-role-arn }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.aws-region }}

      - name: Terraform Init
        run: |
          cd terraform && terraform init

      - name: Terraform Validate
        run: cd terraform && terraform validate

      - name: Terraform Plan
        id: terraform-plan
        run: |
          cd terraform && terraform plan -out="plan.out"

      - name: Terraform Apply
        id: terraform-apply
        run: |
          cd terraform && terraform apply "plan.out"
