name: "Terraform Workflow"

on:
  workflow_call:
    inputs:
      aws-assume-role-arn:
        type: string
        required: true
      

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          cd terraform && terraform init

      - name: Terraform Validate
        run: cd terraform && terraform validate

      - name: Terraform Plan
        id: terraform-plan
        run: |
          cd terraform && terraform plan -out="plan.out"

      - name: Terraform Apply
        id: terraform-apply
        run: |
          cd terraform && terraform apply "plan.out"

      - name: Terraform Destroy (Always Run)
        if: always()  # Isso garante que o comando será executado independentemente do sucesso ou falha dos passos anteriores
        run: |
          cd terraform && terraform destroy -auto-approve
